version: '3'

services:
  docker-rtl-433-mqtt:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    devices:
      - /dev/bus/usb/001/005:/dev/bus/usb/001/005
    network_mode: bridge
  mqtt:
    container_name: mqtt
    image: "eclipse-mosquitto:latest"
    ports:
      - 1902:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      - ./mosquitto/log:/mosquitto/log
