version: '3.8'

services:
  docker-rtl-433-mqtt:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    devices:
      - /dev/bus/usb/001/002:/dev/bus/usb/001/002
    network_mode: bridge
    profiles:
      - app
  mqtt:
    container_name: mqtt
    image: "eclipse-mosquitto:latest"
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      - ./mosquitto/mosquitto.log:/mosquitto/log/mosquitto.log:rw
    profiles:
      - test